### ISSUE TITLE
Orchestra description divs styling

### ISSUE THREAD

**Issue by BlakeSharp** [CBHS-Orchestra-Council-Webmaster/BrookOrchestraWebsite#14]
round all the descriptions with "border-radius" to reduce the amount of blocking on the page. Possibly do the same with the Brady Meyer about section and have it maintain the same animation like the rest of the divs but simply floating. Possibly also add some drop shadow to maintain a floating effect?

**Comment by 04AJ** [comment]
" have it maintain the same animation like the rest of the divs but simply floating.: -Should the image of Mr. Meyer also scale on hover like the other divs? There wasn't anything to click so that's why I didn't add that animation to his img.
