### ISSUE TITLE
Footer consistency

### ISSUE THREAD

**Issue by BlakeSharp** [CBHS-Orchestra-Council-Webmaster/BrookOrchestraWebsite#15]
The footer should be the same for all of the pages. The footer isn't a part of the page itself simply something at the end of each to relay essential information, for that reason I believe it should be the same for every page to maintain some consistency.

**Comment by 04AJ** [comment]
True, but I think for some of the pages (About, Support) keeping the footer would have the same background color as the elements above so there isn't a clear distinction between the body and footer. So, I thought that having a light and dark version of the footer alternate each page would create good contrast between body and footer.
