### ISSUE TITLE
Calendar header

### ISSUE THREAD

**Issue by BlakeSharp** [CBHS-Orchestra-Council-Webmaster/BrookOrchestraWebsite#16]
the Calender label goes into the header on its page. Also, I don't think that there should be an SVG in between the calendar label and the actual calendar because it is simply being labeled, and putting the label in a different section than the actual thing that it is labeling seems odd to me.

**Comment by 04AJ** [comment]
Fixed the label. Tbh I just put the svg to make the page (and the support page) seem less boring o_o Is it too distracting?
