### ISSUE TITLE
Gallery header

### ISSUE THREAD

**Issue by BlakeSharp** [CBHS-Orchestra-Council-Webmaster/BrookOrchestraWebsite#17]
Every other page has a header indicating where you are, the gallery page doesn't. I believe that doing the same as was done to the main page ( making the background images darker and adding the gallery label on top of them ) would serve to add more consistency to the site. Also, there is no indication as to the fact you should scroll down, im not sure as to how to fix that well though.

**Comment by 04AJ** [comment]
Added header to main gallery. For scrolling indication, I was thinking adding vertical radio buttons on the side of the page once another year is added (with its own group picture). The buttons would have labels for the year ('22, or '23) and clicking them would scroll down the page to the group picture for that year.
